[package]
name = "rodin"
version = "0.1.0"
edition = "2024"

[dependencies]
aho-corasick = "1.1.3"
anyhow = "1.0.97"
byteorder = "1.5.0"
clap = "4.5.32"
hex-literal = "1.0.0"
indicatif = "0.17.11"
log = "0.4.26"
memmap2 = "0.9.5"
simplelog = "0.12.2"
